// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// climatch_vec
NumericVector climatch_vec(DataFrame recipient, DataFrame source, NumericVector globvar);
RcppExport SEXP _Euclimatch_climatch_vec(SEXP recipientSEXP, SEXP sourceSEXP, SEXP globvarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type recipient(recipientSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type source(sourceSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type globvar(globvarSEXP);
    rcpp_result_gen = Rcpp::wrap(climatch_vec(recipient, source, globvar));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Euclimatch_climatch_vec", (DL_FUNC) &_Euclimatch_climatch_vec, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_Euclimatch(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
